spring.application.name=ToDo

# URL de conexión: jdbc:postgresql://[host]:[puerto]/[nombre_bd]
spring.datasource.url=jdbc:postgresql://localhost:5432/tasks_db
spring.datasource.username=postgres
spring.datasource.password=12345678

# Driver y Dialecto
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 'update' crea las tablas si no existen o las actualiza sin borrar datos
spring.jpa.hibernate.ddl-auto=update

# Para ver el SQL en consola (útil para debuguear)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true